### ISSUE TITLE
Readme does not mention having to CD into tests directory before running tests

### ISSUE THREAD

**Issue by Synchronicity89** [andrewferlitsch/Gap#101]
Readme does not mention having to CD into tests directory before running tests.  If it is not actually required in the end then the snippets such as pytest -v image_test.py  might have to be  changed to:
pytest -v tests/image_test.py

unless some configuration file is added that helps pytests find the tests there.

The impact is large to testing because many tests appear to fail even if you CD into tests

**Comment by Synchronicity89** [comment]
I used this workaround for my repo by adding the bolded lines of code that changes directory.  Doing that means I can follow the ReadMe file instructions exactly as they are written.


`    def setup_class(self):
        **os.chdir("./tests")**  

    def teardown_class(self):
        **os.chdir("..")** `

**Comment by chrisheckler** [comment]
I will take a look when I get home. Thanks for the heads up.

**Comment by chrisheckler** [comment]
Submitted PR addressing this issue.

**Comment by andrewferlitsch** [comment]
Thanks for looking deeper into this. I know on my Windows box, if I 'cd' into tests and do pytest -v image_test.py it works for me.

**Comment by andrewferlitsch** [comment]
Looks like this is fixed to me (at least the CD part). I verified the README now says to 'cd tests'

If we are having failures in running on some other platform, let's open a separate Issue specific to the platform.
