### ISSUE TITLE
v0.9: Vision: bug when combine 1_100.jpg and test.jpg as a collection from Images class

### ISSUE THREAD

**Issue by andrewferlitsch** [andrewferlitsch/Gap#13]
Setup:
images = Images(['1_100.jpg', 'test.jpg']), 2)

Actual Output:
An error occurs writing the HDF5 file, about an invalid dtype(0)

**Comment by virtualdvid** [comment]
There is a typo error: 'test'jpg' -> 'test.jpg'

**Comment by andrewferlitsch** [comment]
typo fixed

**Comment by andrewferlitsch** [comment]
Fixed in v0.9.2
