### ISSUE TITLE
Quick Start Guide link gives 404

### ISSUE THREAD

**Issue by chrisheckler** [andrewferlitsch/Gap#29]
What I expected:
I expected to click the link and be able to dig around in the User's Guide: User's (Programming) Quick Start Guide

What occurred:
The link:
https://github.com/andrewferlitsch/Gap/blob/master/specs/quick%20start%20guide.docx
resulted in 404 Page Not Found

**Comment by andrewferlitsch** [comment]
Fixed in Gap v0.91
