### ISSUE TITLE
gap-ml --Unable to create attribute (object header message is too large)

### ISSUE THREAD

**Issue by virtualdvid** [andrewferlitsch/Gap#67]
I'm trying to use **gapml** to fit an image dataset into a `keras` model.

After downloading the dataset with:

```
curl http://download.tensorflow.org/example_images/flower_photos.tgz \
    | tar xz -C tf_files
```

I got this results on a jupyter notebook

in[]
```
labels = os.listdir('flower_photos')
print("Number of Labels:", len(labels))
labels = [ 'flower_photos/' + lb for lb in labels] 
print(labels)
```
out[]
```
Number of Labels: 5
['flower_photos/dandelion', 'flower_photos/tulips', 'flower_photos/sunflowers', 'flower_photos/daisy', 'flower_photos/roses']
```

Here is when I got the error:

in[]
`images = Images(labels, [l for l in range(len(labels))], config=['resize=(224,244)'], name='flower')`
out[]
`Unable to create attribute (object header message is too large)`

**Comment by andrewferlitsch** [comment]
fixed by virtualvd
