### ISSUE TITLE
Uncaught exception in vision.py

### ISSUE THREAD

**Issue by chrisheckler** [andrewferlitsch/Gap#79]
While working with my data set for tutorial I passed in a cv2 object with 5 images that was valid previously and printed out the shape of each.

Passing this object into images produced a 'ValueError
Code snippet:
```python
for index in [10,20,30,50,100]:
    print(data[index])

    # Use openCV to read the image into memory as an uncompressed bitmap
    pixels = cv2.imread(labels[0] + '/' + data[index])

    # Let's look at the shape of the image.
    print(pixels.shape)
```
[Output]
1520_2.png
(399, 381, 3)
2_2.png
(399, 381, 3)
489_2.png
(399, 381, 3)
545_2.png
(399, 381, 3)
27_2.png
(399, 381, 3)

```python
images = Images(pixels)
print("TIME", images.time)
```
[Output]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-147-7a44d0a063c6> in <module>()
----> 1 images = Images(pixels)
      2 print("TIME", images.time)

~/miniconda3/envs/env/lib/python3.6/site-packages/gapml/vision.py in __init__(self, images, labels, dir, name, ehandler, config)
    491 
    492         if isinstance(images, list) is False:
--> 493             if isinstance(images, str) is False and not os.path.isdir(images):
    494                 raise TypeError("List or Directory expected for image paths")
    495             # parameter is a directory, convert to list of images in the directory

~/miniconda3/envs/env/lib/python3.6/genericpath.py in isdir(s)
     40     """Return true if the pathname refers to an existing directory."""
     41     try:
---> 42         st = os.stat(s)
     43     except OSError:
     44         return False

ValueError: stat: embedded null character in path
```

**Comment by andrewferlitsch** [comment]
It looks like you forgot to include the labels parameter. But it should give a better exception than what you got! Try:

images = Images(pixels, 1)

**Comment by andrewferlitsch** [comment]
I recall this bug. I already fixed. That section of code was rewritten like 2 days ago.

**Comment by andrewferlitsch** [comment]
verify by Chris it works
