### ISSUE TITLE
train/test image generator from an Images object

### ISSUE THREAD

**Issue by chrisheckler** [andrewferlitsch/Gap#99]
I believe this enhancement would be invaluable.  By enabling close interaction with tools such as Keras the adoption of Gap is more attractive. Usage of an Image generator also would not be limited to Keras.

One convincing usage would be to utilize the  Keras .fit_generator function for inputting very large collection.hdf5 files that are unable to be stored in memory and are fed by batch into a model.Sequence() object.  This function requires a generator which this enhancement would satisfy:
```fit_generator(generator, steps_per_epoch=None, epochs=1, verbose=1, callbacks=None, validation_data=None, validation_steps=None, class_weight=None, max_queue_size=10, workers=1, use_multiprocessing=False, shuffle=True, initial_epoch=0)``` 

generator: A **generator** **or** an instance of Sequence (keras.utils.Sequence) object in order to avoid duplicate data when using multiprocessing. The output of the generator must be either

a tuple (inputs, targets)
a tuple (inputs, targets, sample_weights).

A reference to the keras Sequence class.

```from skimage.io import imread
from skimage.transform import resize
import numpy as np

# Here, `x_set` is list of path to the images
# and `y_set` are the associated classes.

class Sequence(Sequence):

    def __init__(self, x_set, y_set, batch_size):
        self.x, self.y = x_set, y_set
        self.batch_size = batch_size

    def __len__(self):
        return int(np.ceil(len(self.x) / float(self.batch_size)))

    def __getitem__(self, idx):
        batch_x = self.x[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]

        return np.array([
            resize(imread(file_name), (200, 200))
               for file_name in batch_x]), np.array(batch_y)```

**Comment by andrewferlitsch** [comment]
Chris, I still need to come more upto speed on Keras, which will happen over the next couple of weeks. Though the proposal sounds similar to David and my discussion on implementing some caching feature between the HD5 file and memory for given 'spark' like capabilities on a laptop (we dubbed it mini-spark capability).

**Comment by andrewferlitsch** [comment]
This issue is superceded by #111
